[versions]

project = "0.0.0"
java = "21"

netty = "4.2.7.Final"
kala = "0.82.0"
gson = "2.13.2"
jline = "3.30.0"
picocli = "4.7.7"
chart-fx = "11.3.1"
jfreechart = "1.5.6"
guava = "33.5.0-jre"

kotlinx = "1.9.0"
sqlite = "3.51.1.0"

[libraries]

kala-base = { group = "org.glavo.kala", name = "kala-base", version.ref = "kala" }
kala-collection = { group = "org.glavo.kala", name = "kala-collection", version.ref = "kala" }
kala-common = { group = "org.glavo.kala", name = "kala-common", version.ref = "kala" }
kala-gson = { group = "org.glavo.kala", name = "kala-common-gson", version.ref = "kala" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

chart-fx = { group = "io.fair-acc", name = "chartfx", version.ref = "chart-fx" }
jfreechart = { group = "org.jfree", name = "jfreechart", version.ref = "jfreechart" }

jline = { group = "org.jline", name = "jline", version.ref = "jline" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli" }
picocli-codegen = { group = "info.picocli", name = "picocli-codegen", version.ref = "picocli" }

guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }